"""Fully offline check that _prepare_context_queries() produces the right output SHAPE and
behavior against real, previously-captured Stage 1 output — no live API call, no re-scrape.

The fixture (tests/fixtures/search_test_cases_20260708T113409Z.json) was generated by
experiments/generate_search_test_cases.py, which already ran the real Stage 0 scrape + Stage 1
sarvam-30b call for real articles once. It's copied into tests/fixtures/ (tracked in git) rather
than read from experiments/ (gitignored as a scratch workspace, so absent in CI checkouts) so
this test can actually run in GitHub Actions. This test replays that captured entities/gap_queries_raw
straight into the real _prepare_context_queries() function — the same one _synthesize_sarvam()
calls in production — so it's cheap and deterministic to run every time (unlike
tests/test_live_gap_queries.py, which re-hits the live API and is skipped by default), while
still exercising real, not hand-written, model output.

Complements the other two test layers for this fix:
- tests/test_synthesize.py::TestPrepareContextQueries — hand-picked strings, isolates specific
  edge cases (dropped-when-still-dangling, abbreviated entity match, etc.)
- tests/test_live_gap_queries.py — makes a fresh live call, catches whether the underlying
  model's *behavior* has drifted (this file cannot catch that, since the input is frozen)
"""
import json
from pathlib import Path

import pytest

from writer.synthesize import _prepare_context_queries, _query_has_dangling_reference

_FIXTURE_PATH = (
    Path(__file__).resolve().parent / "fixtures" / "search_test_cases_20260708T113409Z.json"
)

with open(_FIXTURE_PATH, encoding="utf-8") as f:
    _ARTICLES = json.load(f)

_MULTI_GAP_ARTICLES = [a for a in _ARTICLES if len(a.get("gap_queries_raw", [])) >= 2]
_MULTI_GAP_IDS = [a["title"][:50] for a in _MULTI_GAP_ARTICLES]


@pytest.mark.parametrize("article", _ARTICLES, ids=[a["title"][:50] for a in _ARTICLES])
def test_output_shape_is_list_of_original_dispatch_pairs(article):
    """Regardless of how many GAP queries an article produced (0 to several), the output must
    always be a list of (original_query, text_actually_dispatched) pairs, a subset of the input
    in original order, never inventing or reordering a query."""
    gap_queries = article["gap_queries_raw"]
    entities = article["entities"]

    result = _prepare_context_queries(gap_queries, entities)

    assert isinstance(result, list)
    assert all(isinstance(pair, tuple) and len(pair) == 2 for pair in result)
    origs = [orig for orig, _dispatch in result]
    assert origs == [q for q in gap_queries if q in origs], "survivors must stay in original GAP order"
    assert set(origs) <= set(gap_queries), "must not invent a query that wasn't in the input"


@pytest.mark.parametrize("article", _MULTI_GAP_ARTICLES, ids=_MULTI_GAP_IDS)
def test_dispatched_text_is_always_free_of_dangling_references(article):
    """The core property this whole fix exists for: whatever text actually gets sent to the
    search/research backend must be self-contained, even when the raw GAP query wasn't."""
    gap_queries = article["gap_queries_raw"]
    entities = article["entities"]
    entity_names = [e["name"] for e in entities if e.get("name")]

    result = _prepare_context_queries(gap_queries, entities)

    print(f"\n[{article['title'][:60]}]")
    for orig, dispatch in result:
        tag = "CONTEXT-ATTACHED" if dispatch != orig else "unchanged       "
        print(f"  {tag} : {orig}")
        if dispatch != orig:
            print(f"      -> dispatched as: {dispatch}")
        assert not _query_has_dangling_reference(dispatch, entity_names), (
            f"dispatch text is still dangling even after _prepare_context_queries: {dispatch!r}"
        )

    dropped = set(gap_queries) - {orig for orig, _ in result}
    for q in dropped:
        print(f"  DROPPED          : {q}")


def test_gitlost_gap2_gets_gap1_attached_as_context_not_dropped():
    """The exact real regression case this fix was built for (see CLAUDE.md, 2026-07-08): GAP2
    never names "GitLost" or any other entity on its own ("...how does this differ from a
    standard repository access control bypass?"). Verifies the fix's actual behavior against
    the real captured fixture, not a hand-retyped copy of it: GAP2 must survive (not be dropped)
    and must come out with GAP1's text attached as background context."""
    article = next(a for a in _ARTICLES if a["title"].startswith("GitLost"))
    gap_queries = article["gap_queries_raw"]
    entities = article["entities"]
    assert len(gap_queries) == 3, "fixture shape changed — re-check this test still applies"

    gap1, gap2, gap3 = gap_queries
    result = _prepare_context_queries(gap_queries, entities)
    dispatch_by_orig = dict(result)

    assert set(dispatch_by_orig) == {gap1, gap2, gap3}, "nothing should be dropped in this case"
    assert dispatch_by_orig[gap1] == gap1, "GAP1 itself is never rewritten"
    assert dispatch_by_orig[gap2] != gap2, "GAP2 is the dangling one and must be rewritten for dispatch"
    assert gap1 in dispatch_by_orig[gap2], "GAP1's text must be attached so GAP2 can resolve on its own"
    assert dispatch_by_orig[gap3] == gap3, "GAP3 already names 'GitHub Agentic Workflows' — left unchanged"
